[Basics]
downloadPath = "/tmp/"
colorless = false
# The prefix before evaluating a command
cmdPrefix = "/"

[Formatting]
# BASH-like PS1 variable equivalent
outputFormat = "┌──[$USER@$DEVICE] [$ID] [$DATE - $TIME]\n└╼ $MSG"

# 02 = Day, Jan = Month, 06 = Year
dateFormat = "02Jan06"

# 15 = hours, 04 = minutes, 05 = seconds
timeFormat = "15:04"


[Colors]
	 [Colors.channels]
		  [Colors.channels.basic]
		  foreground = "normal"
		  [Colors.channels.header]
		  foreground = "magenta"
		  bold = true
		  [Colors.channels.unread]
		  foreground = "green"
		  italic = true

	 [Colors.message]
		  [Colors.message.body]
		  foreground = "normal"
		  [Colors.message.header]
		  foreground = "grey"
		  [Colors.message.mention]
		  foreground = "green"
		  italic = true
		  bold = true
		  [Colors.message.id]
		  foreground = "yellow"
		  [Colors.message.time]
		  foreground = "magenta"
		  [Colors.message.sender_default]
		  foreground = "cyan"
		  bold = true
		  [Colors.message.sender_device]
		  foreground = "cyan"
		  [Colors.message.attachment]
		  foreground = "red"
		  [Colors.message.link_url]
		  foreground = "yellow"
		  [Colors.message.link_keybase]
		  foreground = "yellow"
		  [Colors.message.reaction]
		  foreground = "magenta"
		  bold = true
		  [Colors.message.code]
		  foreground = "cyan"
		  background = "grey"
	 [Colors.feed]
		  [Colors.feed.basic]
		  foreground = "grey"
		  [Colors.feed.error]
		  foreground = "red"